# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ffd58fad17ae7aaba907e317eebbd9047887ff4a2f5e6a99c984ec522df459c52a4e1c81f6d16f61c27ff9bc9e19d000b7b83b72aaf8658e062177d411ba79a5
  omni_file: config/omniauth.yml

test:
  secret_key_base: 14e5342fdc53557a9fd4096da23b4e8ac4613909bff25211aad8592306cebe41520a2e5acb68f1ad64b3571e6a4d1918d22b1bea153587705b8762920e3b7b6c
  omni_file: config/omniauth.yml

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

# Secret are overridden in deployment process.

production:
  secret_key_base: ffd58fad17ae7aaba907e317eebbd9047887ff4a2f5e6a99c984ec522df459c52a4e1c81f6d16f61c27ff9bc9e19d000b7b83b72aaf8658e062177d411ba79a5
  omni_file: config/omniauth.yml
